# Generated by Django 4.1.3 on 2022-12-02 17:09

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=groups.models.generate_code, editable=False, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.applists')),
                ('members', models.ManyToManyField(to='accounts.profile')),
            ],
        ),
    ]
