# Generated by Django 4.1.3 on 2022-12-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applists',
            name='is_billing',
            field=models.BooleanField(default=True),
        ),
    ]
